server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mysql?useUni=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
#     driver-class-name: com.mysql.jdbc.Driver # mysql 5버전